server:
  port: 6020
eureka:
  client:
    serviceUrl:
      defaultZone: http://server-eureka:2lvoHcfXbXmTBvQm@localhost:1000/eureka
  instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
logging:
  config: classpath:logback.xml
spring:
  application:
    name: cssm-server-zuul
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  security:
    basic:
      enabled: true
    user:
      name: server-zuul
      password: 35446Q3QJS7UvVdN
#禁用SendErrorFilter过滤器，此过滤器会跳转错误页面，导致结果输出不了
#SendErrorFilter里面的dispatcher.forward(request, ctx.getResponse())会启用writer，导致post里面write返回结果的时候报错：
#Java.lang.IllegalStateException: getWriter() has already been called for this response
zuul:
  routes:
    cssm-application-user:
      path: /user/**
      stripPrefix: false
    cssm-application-common:
      path: /common/**
      stripPrefix: false
    cssm-application-operation:
      path: /operation/**
      stripPrefix: false
    cssm-application-wechat:
      path: /wechat/**
      stripPrefix: false
    cssm-application-interaction:
      path: /interaction/**
      stripPrefix: false
    cssm-application-task:
      path: /task/**
      stripPrefix: false
    cssm-application-mq:
      path: /mq/**
      stripPrefix: false
    cssm-application-third:
      path: /third/**
      stripPrefix: false
  SendErrorFilter:
    error:
      disable:
        true
  sensitive-headers: "*"

#配置超时时间，断点调试，上传大文件等容易超时
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 126000

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000



