spring:
  application:
    name: cssm-server-eureka
  security:
    basic:
      enabled: true
    user:
      name: server-eureka
      password: 2lvoHcfXbXmTBvQm
logging:
  config: classpath:logback.xml

server:
  port: 1000
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://server-eureka:2lvoHcfXbXmTBvQm@${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}